name: Deploy Chatbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Create deployment package from src/
      run: |
        cd src
        zip -r ../deployment.zip .

    - name: Validate S3 bucket name
      run: |
        if [ -z "${{ env.S3_BUCKET }}" ]; then
          echo "Error: S3_BUCKET environment variable is empty"
          exit 1
        fi
        echo "Using S3 bucket: ${{ env.S3_BUCKET }}"

    - name: Upload deployment.zip to S3
      run: |
        aws s3 cp deployment.zip "s3://${{ env.S3_BUCKET }}/deployment.zip"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -var="lambda_function_name=${{ secrets.LAMBDA_FUNCTION_NAME }}" \
                       -var="s3_bucket=${{ secrets.S3_BUCKET }}" \
                       -var="deployment_package_key=deployment.zip"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: |
        cd terraform
        terraform apply -auto-approve -var="lambda_function_name=${{ secrets.LAMBDA_FUNCTION_NAME }}" \
                        -var="s3_bucket=${{ secrets.S3_BUCKET }}" \
                        -var="deployment_package_key=deployment.zip"
