name: Import Terraform Resources

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Import S3 Bucket
      working-directory: terraform
      run: terraform import aws_s3_bucket.lambda_bucket "${{ secrets.S3_BUCKET }}"

    - name: Import IAM Role
      working-directory: terraform
      run: terraform import aws_iam_role.lambda_role "${{ secrets.LAMBDA_ROLE_NAME }}"

    - name: Import IAM Policy
      working-directory: terraform
      run: terraform import aws_iam_policy.lambda_bedrock_policy $(terraform output -raw lambda_bedrock_policy_arn) 